#!/usr/bin/env node
/**
 * Emit `.lycheeignore` patterns for URLs we have deliberately declined.
 *
 * `review_ack.website` records a URL reviewed and rejected — usually a dead site
 * removed from `website` so the page invites a replacement instead of linking
 * somewhere broken. The URL stays in the YAML on purpose (that is what stops the
 * importer refilling it), and the monthly link check scans whole files, so
 * without this the links we just removed get reported as broken again every
 * month.
 *
 * A `not_running` entry's own `website` is excluded for the same reason: an
 * edition that is not taking place routinely has a homepage that has already
 * gone (a rejected proposal's site is often deleted outright), and there is no
 * fix to make — the entry is a tombstone by design, so a monthly "broken link"
 * report on it is pure noise.
 *
 * Run from the link-check workflow, appending to `.lycheeignore`:
 *   node scripts/lychee_exclusions.mjs >> .lycheeignore
 *
 * Self-maintaining: declining another URL adds it here automatically, and
 * re-adopting one removes it.
 *
 * Deliberately dependency-free — no js-yaml, no lib/ imports. The link-check
 * workflow is a lightweight job with no `npm ci`, and making it install the tree
 * just to list a dozen URLs would cost more than the check itself. The files are
 * machine-written with two-space indentation, so a scan for `website:` inside the
 * `review_ack:` block is enough.
 */
import fs from 'node:fs';
import path from 'node:path';

const DIR = new URL('../data/workshops/', import.meta.url).pathname;
const escapeRe = (s) => String(s).replace(/[.*+?^${}()|[\]\\/]/g, '\\$&');

const urls = new Set();
for (const file of fs.readdirSync(DIR).filter((f) => f.endsWith('.yml'))) {
  let inAck = false;
  let notRunning = false;
  let ownWebsite = null;
  for (const line of fs.readFileSync(path.join(DIR, file), 'utf8').split('\n')) {
    // Top-level keys carry no indentation, so these two tests cannot be confused
    // with the same key nested inside `review_ack:`.
    if (/^not_running:\s*$/.test(line)) notRunning = true;
    const own = line.match(/^website:\s*["']?(https?:\/\/[^"'\s]+)["']?\s*$/);
    if (own) ownWebsite = own[1];

    if (/^review_ack:\s*$/.test(line)) { inAck = true; continue; }
    if (inAck && !/^\s/.test(line)) inAck = false;      // dedent ends the block
    if (!inAck) continue;
    const m = line.match(/^\s+website:\s*["']?(https?:\/\/[^"'\s]+)["']?\s*$/);
    if (m) urls.add(m[1]);
  }
  if (notRunning && ownWebsite) urls.add(ownWebsite);
}

if (urls.size) {
  console.log('');
  console.log('# --- generated by scripts/lychee_exclusions.mjs; do not edit by hand ---');
  console.log('# URLs recorded in `review_ack.website`: reviewed, declined, and kept in the');
  console.log('# data only so the importer does not restore them. Not links we publish.');
  console.log('# Plus the `website` of every `not_running` entry: a tombstoned edition\'s');
  console.log('# homepage is routinely gone, and there is no fix to report.');
  for (const u of [...urls].sort()) console.log(escapeRe(u));
}
